# Generated by Django 3.2.5 on 2021-07-08 12:07

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth_', '0002_following'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='following',
            unique_together={('follower', 'following')},
        ),
    ]
